name: CI/CD for Kittygram

on:
  push

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print project tree
        run: tree .
